* Group 4
** Interview Script
*** Segments
**** Beginnning news like intro segment
***** Intro Monologue
We have all become accustomed to this new situation which has spread
over us as fast as the nachos disappear from the bowl that I told no
one to touch. In all the mess of lockdown and social distancing, we
all may be happy to have an excuse to stay away from that eccentric
neighbor who never wears perfume but this seemingly unclimbable wall
has also kept us away from friends and the people we actually care
about. Lets get to know how these new changes have affected the
younger generation by asking the important questions questions:

- How has this pandemic affected the lives of schoolgoing children?
- What changes will we see next?
- Why didn't I get the purple nachos instead?

Clearly, one of those questions is the most puzzling of the bunch. To
answer the other 2. We have with us some High schoolers from
shikshantar school south city 1 gurgaon who have agreed to help us
understand how this pandemic has put a twist on the already stressful
life of a 9th grader.
***** General
We have with us today, why don't you all introduce yourselves?

Advait:
Hp:
Suhani:

Now for you all, we have some very interesting questions lined up
today, but before all that why don't you tell out audience about how
you have kept up with COVID in the last few months

~im advait, an average high school student who survived covid (edited)~


Splendid, Splendid, rather wonderful person a, how about you person b

~hi.............im harpuneet............also known as hp by some.....(can i go now)~


Marvellous, person c?

Suhani answer

Wodnerful wonderful. Now let us move on to the main objective of this
show, that is ofcourse the questions!

***** Question 1
So, Advait, Could you tell us a little about the bonds with your peers through the ongoing pandemic situation?

~Advait Answer~ :Bonds before the pandemic were very different, I didn't
know the significance of the 5-10 year old relationships I had with my
friends. I just talked to them, played games, nothing more than that.
When Corona locked us in our homes, I missed every friend I had, I
understood the value of each and every friend I had, and I guess they
did too. Honestly, I might have forgotten about a few friends but with
most, I’ve learnt the fact that keeping the strongest bond with them
is one of my utmost priorities because these are the people that can
really make me happy and enjoy life.

Do you think digital technology will continue to have a positive
impact on the relationships within our society or will we lose the
nuance that is inherent in physical speech, like facial expressions
and motions?

~You see, having everything online just helped us realise the
importance of these relationships, the development of a relationship
is always better when there's an exchange of thought not only in the
way of a statement and a reply to that statement but tone of voice,
expressions represented on the face and sometimes just silence too~

***** Question 2
Suhani san, Reflect on your relationship with your peers. Have you been able to sustain?

~Suhani san Answer~

***** Question 3
Hp kun, So before we discuss the challenges that came up during the
pandemic, first let’s hear about what kinds of relationships you have
had with people, how comfortable or difficult has it been to deal with
various perspectives, views and opinions? 

~I have always felt like one of the best things about interacting with
other people is the introduction to different perspectives and
views. I have always tried to be open-minded because if you dont talk
to people its very easy to start thinking that your opinion is always
right and you will end up with a constricted point of view of the
world and so its really important to listen to other peoples opinions
as well and consider their takes and thoughts. sometimes it was a
little difficult to pay a lot of attention to someone elses
perspective but when I actually did I realised that there are a lot of
things that others can think of that I cannot as everyone has
different levels of imagination and different experiences and everyone
has a different thought process so its important to take some pieces
from all of the sources to complete the puzzle. so yeah I have mostly
found dealing with different perspectives pretty comfortable though i
will try and be even more open minded in the future and I think
everyone else should too~



~Do you think someones perspective affects the way you view them?~

Yeah, I think being open-minded can not only help you make better
decisions or learn about stuff in more detail but also provide an
insight to the kind of people they are and what they want and what
they believe is right. I always found it really important that you try
and be open-minded if you want to have good relations.

~Have you ever felt like your opnion was not considered fairly or that
you were not given a chance to voice your thoughts clearly~

No, I would say everyone around me has also been very considerate about
my views on things and they have always let me voice my opinion and
have respected it. Sometimes when people have conflicting opinions
they might try to undermine each others views in order to prove that
their view is right but thats normal and everyone does that but I
never felt like my opinion was ignored or was not acknowledged.

**** CANCELED Flash Quiz -
State "CANCELED" from "TODO" [2022-01-27 Thu 16:54] \\ We think it'll
take too long and didi won't approvve of the tangent 
***** Rules and Prize 

Oh whats that? Oh we're very sorry to interrupt you preson c,
but I we must move on the to the next segment of our show tonight, THE
FLASH QUIZ ~Intro music~ Int his quiz, are participants will be
fighting against the clock, and ofcourse each other to answer our
flash question. The question will be revealed and participants may
press the buzzer. The first to press the buzzer will get to answer the
question. But be ware, an incorrect answer will have you disqualified!
The last one left standing will take away the grand prize! ~prize
reveal~ 
***** Question 1 What is the most prized possesion of a modern teenager? 
***** Question 2 What is commonly reffered to as the best medicine? Memes 
***** Question 3 What do you call a person who follows the ideals of Karl Marx? Simp 
***** Question 4 What is the name for mod of the largest discord server in the world? Simp 
***** Question 5 What does one call the patient of the most common disease in the 2000s? Simp
**** On-Site visit
**** Very sad interview with suhani san
** AOT Theme
** AI Voices
** Ideas
** TODO if you could describe your current life in one word,what wud it be
** TODO am i getting payed for this?
